# Generated by Django 5.2.11 on 2026-02-20 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="grace_until",
            field=models.DateTimeField(
                blank=True, help_text="Reconnection grace deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="reconnect_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="session",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Session summary recorded on end"
            ),
        ),
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_about_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="readings.session",
                    ),
                ),
            ],
        ),
    ]
