# Generated by Django 5.2.11 on 2026-02-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="delivery_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
